sudo: required

notifications:
  email:
    recipients:
      - build@edgefund.net
    on_success: never
    on_failure: always

branches:
  only:
  - master

language: node_js

node_js:
  - "8"

services:
  - docker

before_install:
  - docker pull trufflesuite/ganache-cli
  - docker run -d -p 8545:8545 trufflesuite/ganache-cli:latest -h 0.0.0.0

install:
  - npm install -g truffle
  - npm install -g coveralls
  - npm install

script:
  - ./node_modules/.bin/eslint test/**/*.js
  - npm run coverage && cat coverage/lcov.info | coveralls

deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x deploy.sh && ./deploy.sh
    on:
      branch: master

  - provider: npm
    skip_cleanup: true
    email: "gareth@edgefund.net"
    api_key: $NPM_TOKEN
    on:
      tags: true
