sudo: required

notifications:
  email:
    recipients:
      - build@edgefund.net
    on_success: never
    on_failure: always

branches:
  only:
  - master

language: node_js

node_js:
 - "8"

services:
  - docker

before_install:
  - docker pull trufflesuite/ganache-cli
  - docker run -d -p 8545:8545 trufflesuite/ganache-cli:latest -a 10 -h 0.0.0.0

install:
  - npm install -g truffle
  - npm install -g coveralls
  - npm install

script:
  - ./node_modules/.bin/eslint test/**/*.js
  - truffle test

after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls

deploy:
  provider: script
  script: truffle migrate -f 3 --network rinkeby # 3 refers to migrations/3_deploy_cointoss.js
  on:
    tags: true
    branch: master
